### ISSUE TITLE
Adapt / write documentation

### ISSUE THREAD

**Issue by ladc** [ladc/lgsl#12]
What is the best way to do this and allow it to be merged back into GSL Shell later on?

**Comment by ladc** [comment]
@franko I'm not entirely satisfied with rst / Sphinx because it imposes a Pythonesque OO module structure. Do you want to stick with it in the future? Or is there room for alternatives?

**Comment by franko** [comment]
Hi Lesley,

I'm open to all the alternatives if you find something as convenient as Sphinx and if it does fit better Lua it can be interesting.

**Comment by ladc** [comment]
Oh, it seems that someone specified a [Lua Domain](https://github.com/haka-security/sphinx-lua) for Sphinx. I'll give that a spin first!

**Comment by ladc** [comment]
It appears that the Lua domain breaks some other stuff, so I'll have to tolerate the page titled "Python Module Index" for now ;-)

**Comment by franko** [comment]
I've never noticed the "Python Module Index" thing before and it took me some time to found it.
As usual I overlook a lot of details that you don't miss :-)
