### ISSUE TITLE
Documentation in HTML form on github.io

### ISSUE THREAD

**Issue by franko** [ladc/lgsl#15]
I think it could be useful to host the LGSL documentation on github.io. This is quite easy to do and I can help if you want.

If we choose to use just the default sphinx theme everything can be done in one hour.

**Comment by ladc** [comment]
Sounds good, thanks! I'm still sifting through the doc pages and adding/modifying some stuff where necessary.

**Comment by ladc** [comment]
OK, I'm more or less ready with the docs. I've added a "make doc" rule; works here.

**Comment by ladc** [comment]
I've put a website up [here](http://lgsl.duckdns.org/) for now.

**Comment by franko** [comment]
Cool! Any specific reason to not use github.io ?

**Comment by ladc** [comment]
Not really, just that I had already set up that location. 
I've just tried to create http://ladc.github.io/lgsl but it seems that the CSS files can't be read, any ideas?

**Comment by franko** [comment]
An obscure problem with dr Jekyll I already stumbled on! (wondering if this statement is correct)

I sent a pull request to fix it :-)

**Comment by ladc** [comment]
I wonder what business dr Jekyll has with our documentation ;-)  

Thanks! I don't see any pull requests (yet) though?

**Comment by ladc** [comment]
Fixed (801c21d7).
