### ISSUE TITLE
crash with bspline demo

### ISSUE THREAD

**Issue by franko** [ladc/lgsl#4]
The bspline demo systematically crash on both Windows and Linux.

**Comment by franko** [comment]
Hi Lesley,

after some investigation I've found that:
- the bspline demo crash inside the "linfit" call
- "linfit" crash inside the call gsl_multifit_linear when calling a GSL CBLAS function
- gdb indicates that the dynamic linker is not able to resolve the CBLAS function called by gsl_multifit_linear

My idea now is that the CBLAS library is simply not loaded. Actually if you call "ldd" on the GSL library I obtain:

```
    linux-gate.so.1 =>  (0xb76f4000)
    libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb740f000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7260000)
    /lib/ld-linux.so.2 (0xb76f5000)
```

so the GSL dynamic library does not depend on the gsl cblas DLL.

I have tried to create a GSL DLL that includes the GSL CBLAS and the bug disappears.

Now we need to find a reliable solution. May be we have to ask to the GSL mailing list or to some dynamic linking guru or maybe to Mike Pall :-)

PS: also the "graph" module crash is luajit ends when some plots are still alive but this is a bug of the graphics toolkit.

**Comment by ladc** [comment]
Thanks for the investigation! I suspected as much from the gdb backtrace... I was hoping this could be remedied with an `ffi.load("blas",true)` or `ffi.load("gslcblas",true)`, but alas. It also seems odd that LuaJIT would segfault like that; I've seen it throw a neat "luajit: symbol lookup error [...]" before.

**Comment by ladc** [comment]
There's a solution, but it's pretty ugly....

```
ffi.cdef[[
void *dlopen(const char *filename, int flag);
]]
ffi.C.dlopen("/usr/lib/libblas.so", 0x0102)
```

**Comment by franko** [comment]
I did find another solution even more ugly. It was to create a Lua C Api based module that was just forcing the loading of the GSL and BLAS library. It was working but I didn't like a lot because it was ugly and introduced a C file to be compiled complicating all the build & install stuff.

I believe the solution you found is _The Solution_ :-) and probably we have to go ahead with that. Since the GSL library does not enforce the loading of the BLAS library we load it explicitly. Full Stop. :-)

You are going to commit that in the repository ? I would like to get rid of that problem to start working on more interesting things. I suggest also that we open a "trello" page to discuss the things we want to do. We can close the page later if the development slows down of stop (like we made before with gsl shell).

**Comment by ladc** [comment]
That works for me. One problem is that the path to libblas has to be hardcoded in the dlopen call... And I don't know how to fix it on Windows (or Mac, for that matter).

**Comment by ladc** [comment]
I thought I had solved the issue, but apparently CentOS has a different libblas.so, which doesn't contain the necessary symbols. Instead they are in libgslcblas.so. Sigh.

@franko, I suppose it still crashes on Windows? Do you know if there's a Windows alternative for the dlopen workaround? LoadLibrary doesn't seem to have a lot of options.

**Comment by franko** [comment]
On Windows everything works just fine for me but I'm using a GSL library that includes the OpenBLAS library, so I've actually removed the dlopen call to open the BLAS library.

On Windows this seems to be an interesting option since it does simplify the installation and it does provided an highly optimized BLAS implementation.

Probably what is important for LGSL on windows is to provide:
- a set of working binaries
- install informations for the expert users that may wish to use its own BLAS library or just compile the software by themselves

**Comment by ladc** [comment]
I'm going to split this up into some new issues.
