### ISSUE TITLE
Matrix indexing is slow

### ISSUE THREAD

**Issue by ladc** [ladc/lgsl#7]
Operations like `A[i][j] = A[i][j]*x` are slow. New matrices (views) are created and, eventually, garbage collected. Perhaps add faster methods (`get`,`set`)?

**Comment by franko** [comment]
Hi Lesley,

certainly the matrix indexing is slow and should be avoided in tight loops and the methods "get" and "set" already exists for this reason.

Of course I was quite afraid of this _problem_ but didn't have any good solution to solve the issue. This was actually one of the main reasons that brought me to the design of a language extensions. It is already implemented in gsl shell albeit in the development branch.

You can write m[i, j] and is translated to m.data[m.tda \* i + j] just like a language like fortran is doing (I think).

**Comment by ladc** [comment]
Oh, I somehow overlooked those. I was thinking about a call metamethod but that could only be used for retrieval, of course. I suppose this will do :-)

**Comment by ladc** [comment]
On a related note, any objections if I let `m:set(i,j,x)` and friends return `m`?

**Comment by franko** [comment]
Not sure about that, may be it can be confusing. You are thinking of chaining the function calls à-la javascript ?

**Comment by ladc** [comment]
Yes, I think chaining could be useful here (though I wasn't thinking of JS ;-))
Or simply allowing one to `return m:set(1,1,0)`. Right now `set` doesn't return anything useful anyway.

But I see how it could be confusing, if the user doesn't realise that the returned matrix is the same object as the original one.

**Comment by franko** [comment]
In general, when in doubt, I prefer to keep things simple :-)

The call to m:set perform an operation on the matrix itself and so it seems natural that it does not return anything.

**Comment by ladc** [comment]
OK, I'll leave it as it is now. Thanks for the input.
