### ISSUE TITLE
Harmonize return values of lgsl modules.

### ISSUE THREAD

**Issue by ladc** [ladc/lgsl#9]
For consistency, all modules should return a table (possibly callable with metatable magic, if necessary). Currently some return functions, others return tables. 

See also: [Pierre's module policy](http://blog.separateconcerns.com/2014-01-03-lua-module-policy.html).

**Comment by franko** [comment]
Hi,

I've given a look at the policy and I agree with all the suggestions. I didn't respect it for the module containing just one function but I think it is better to be coherent.

Let me know if you want some help to fix that. I'm quite busy at the moment but I can always spare some time.

**Comment by ladc** [comment]
Fixed in 674f06240.
